version: '3'

services:
  web:
    image: nginx:alpine
    container_name: portfolio-final
    ports:
      - "80:80"
    volumes:
      - /home/<user>/web-challenge:/usr/share/nginx/html
    restart: always
